// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"microservice/client/models"
)

// AddNewProductReader is a Reader for the AddNewProduct structure.
type AddNewProductReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddNewProductReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddNewProductOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddNewProductOK creates a AddNewProductOK with default headers values
func NewAddNewProductOK() *AddNewProductOK {
	return &AddNewProductOK{}
}

/*AddNewProductOK handles this case with default header values.

A list of products returs in the response
*/
type AddNewProductOK struct {
	Payload []*models.Product
}

func (o *AddNewProductOK) Error() string {
	return fmt.Sprintf("[POST /products][%d] addNewProductOK  %+v", 200, o.Payload)
}

func (o *AddNewProductOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *AddNewProductOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
